"""Instruments table added

Revision ID: 040aaeb85cd4
Revises: 0c64ce129af6
Create Date: 2026-06-06 17:15:00.198832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040aaeb85cd4'
down_revision: Union[str, Sequence[str], None] = '0c64ce129af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('asset_class', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('multiplier', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.alter_column('trades', 'instrument_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='instrument_id::uuid')
    op.create_foreign_key(None, 'trades', 'instruments', ['instrument_id'], ['instrument_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.alter_column('trades', 'instrument_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('instruments')
    # ### end Alembic commands ###
