"""Book-level alpha / beta metrics.

Metrics are computed per book (not per trade). The synthetic benchmark tick
(``MARKET_INDEX``) generated by the market-data-service acts as the sampling
clock: on every benchmark observation we snapshot the current market value of
each book and the benchmark level, turn both into simple returns and keep a
rolling window of the aligned ``(book_return, benchmark_return)`` pairs.

For a book with a rolling window of returns:

    beta  = cov(book_returns, benchmark_returns) / var(benchmark_returns)
    alpha = mean(book_returns) - beta * mean(benchmark_returns)

Because covariance and variance share the same denominator, using the
population estimator (divide by N) is equivalent to the sample estimator
(divide by N-1) for beta, so we use the population form for both.
"""

import logging
import os
import threading
from collections import defaultdict, deque
from datetime import datetime, timezone
from typing import Any

# Rolling window length (number of aligned observations). Configurable so the
# assignment's "e.g. last 100 observations" can be tuned without a code change.
WINDOW = int(os.getenv("BOOK_METRICS_WINDOW", "100"))

# Minimum number of aligned observations before alpha/beta are meaningful.
MIN_OBSERVATIONS = 2

book_metrics_cache_lock = threading.Lock()

# book_id -> deque[(book_return, benchmark_return)], aligned and rolling.
book_returns = defaultdict(lambda: deque(maxlen=WINDOW))

# Last sampled values, used to turn levels into simple returns.
last_book_value = {}          # book_id -> float (last book market value)
last_benchmark_level = {"value": None}

# book_id -> latest computed metrics dict, served by the API.
metrics_store = {}


def mean(values):
    return sum(values) / len(values)


def covariance(xs, ys, mean_x, mean_y):
    return sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys)) / len(xs)


def variance(values, mean_value):
    return sum((v - mean_value) ** 2 for v in values) / len(values)


def snapshot_book_values():
    """Aggregate the latest per-trade valuations into a market value per book.

    A book's value is the sum of the latest ``fair_value`` of every trade that
    belongs to it (fair_value already embeds quantity and multiplier), i.e. the
    current mark-to-market value of the whole book.
    """
    import calculation_service

    book_values = defaultdict(float)
    with calculation_service.pricing_lock:
        valuations = list(calculation_service.valuations_store.values())

    for valuation in valuations:
        book_id = valuation.get("book_id")
        fair_value = valuation.get("fair_value")
        if book_id is None or fair_value is None:
            continue
        book_values[book_id] += float(fair_value)

    return book_values


def compute_metrics(book_id, pairs):
    book_returns = [p[0] for p in pairs]
    benchmark_returns = [p[1] for p in pairs]

    mean_book = mean(book_returns)
    mean_benchmark = mean(benchmark_returns)
    var_benchmark = variance(benchmark_returns, mean_benchmark)

    if var_benchmark == 0:
        beta = None
        alpha = None
    else:
        cov = covariance(book_returns, benchmark_returns, mean_book, mean_benchmark)
        beta = cov / var_benchmark
        alpha = mean_book - beta * mean_benchmark

    return {
        "book_id": book_id,
        "alpha": round(alpha, 8) if alpha is not None else None,
        "beta": round(beta, 8) if beta is not None else None,
        "observations": len(pairs),
        "window": WINDOW,
        "avg_book_return": round(mean_book, 8),
        "avg_benchmark_return": round(mean_benchmark, 8),
        "benchmark_symbol": "MARKET_INDEX",
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }


def extract_benchmark_level(tick):
    """Read and validate the benchmark level from a tick; None if unusable."""
    index_level = tick.get("last")
    if index_level is None:
        logging.warning(f"Benchmark tick without a level, skipping: {tick}")
        return None
    return float(index_level)


def simple_return(current_value, previous_value):
    """Simple return of current vs previous; None if it cannot be formed."""
    if previous_value is None or previous_value == 0:
        return None
    return (current_value - previous_value) / previous_value


def seed_initial_levels(book_values):
    """Remember the current book levels so the next tick can form returns.

    Must be called while holding ``book_metrics_cache_lock``.
    """
    for book_id, book_value in book_values.items():
        last_book_value[book_id] = book_value
    logging.info("Seeded benchmark/book levels for alpha/beta (first observation).")


def update_book_metrics(book_id, book_value, benchmark_return):
    """Append a new aligned return pair for a book and refresh its alpha/beta.

    Must be called while holding ``book_metrics_cache_lock``.
    """
    prev_book_value = last_book_value.get(book_id)
    last_book_value[book_id] = book_value

    book_return = simple_return(book_value, prev_book_value)
    if book_return is None:
        return

    book_returns[book_id].append((book_return, benchmark_return))

    book_pairs = book_returns[book_id]
    if len(book_pairs) < MIN_OBSERVATIONS:
        return

    metrics = compute_metrics(book_id, list[Any](book_pairs))
    metrics_store[book_id] = metrics
    logging.info(
        f"Book {book_id} metrics updated: alpha={metrics['alpha']}, "
        f"beta={metrics['beta']}, observations={metrics['observations']}"
    )


def on_benchmark_tick(tick):
    """Sample all books against a new benchmark observation and refresh metrics."""
    index_level = extract_benchmark_level(tick)
    if index_level is None:
        return

    book_values = snapshot_book_values()

    with book_metrics_cache_lock:
        prev_level = last_benchmark_level["value"]
        last_benchmark_level["value"] = index_level

        # Need two benchmark points to form the first return.
        if prev_level is None or prev_level == 0:
            seed_initial_levels(book_values)
            return

        benchmark_return = simple_return(index_level, prev_level)

        for book_id, book_value in book_values.items():
            update_book_metrics(book_id, book_value, benchmark_return)


def get_all_metrics():
    with book_metrics_cache_lock:
        return {book_id: dict(metrics) for book_id, metrics in metrics_store.items()}


def get_metrics_for_book(book_id):
    with book_metrics_cache_lock:
        metrics = metrics_store.get(book_id)
        return dict(metrics) if metrics is not None else None
